# Generated by Django 5.2.7 on 2025-10-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_strings', to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descriptions', models.ManyToManyField(blank=True, related_name='context_type_of_description', to='main.languagestring')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True)),
                ('descriptions', models.ManyToManyField(blank=True, related_name='situations', to='main.languagestring')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations_for_language', to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descriptions', models.ManyToManyField(blank=True, related_name='prompts', to='main.languagestring')),
                ('situations', models.ManyToManyField(blank=True, related_name='prompts', to='main.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('shouldBeExpressed', models.BooleanField()),
                ('shouldBeUnderstood', models.BooleanField()),
                ('descriptions', models.ManyToManyField(blank=True, related_name='communications', to='main.languagestring')),
                ('situations', models.ManyToManyField(blank=True, related_name='communications_of_situation', to='main.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('transliteration', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances_of_communication', to='main.communication')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=255)),
                ('descriptions', models.ManyToManyField(blank=True, related_name='context_of_description', to='main.languagestring')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='main.utterance')),
            ],
            options={
                'verbose_name_plural': 'contexts',
            },
        ),
    ]
