# Generated by Django 5.2.7 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_situation_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='target_languages',
            field=models.ManyToManyField(blank=True, related_name='situations_available_as_target', to='main.language'),
        ),
    ]
