# Generated by Django 5.2.7 on 2025-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_situation_target_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='context',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='contexttype',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='communication',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contexttype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
